
export default new Map([
["src/content/post/top-14-free-icon-libraries-for-designers-and-developers/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Ftop-14-free-icon-libraries-for-designers-and-developers%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/post/design-style-guide-spacepunk/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Fdesign-style-guide-spacepunk%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/post/design-style-guide-neo-brutalism/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Fdesign-style-guide-neo-brutalism%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/post/what-have-I-developed-as-a-designer/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Fwhat-have-I-developed-as-a-designer%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/post/design-style-guide-retro-and-vintage/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Fdesign-style-guide-retro-and-vintage%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/post/web-design-style-guide-brutalism/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Fweb-design-style-guide-brutalism%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/post/the-aesthetics-of-time-dislocation-retro-futurism/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Fthe-aesthetics-of-time-dislocation-retro-futurism%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/post/personal-website-selection-guide-for-designers/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpost%2Fpersonal-website-selection-guide-for-designers%2Findex.mdx&astroContentModuleFlag=true")]]);
		